{% set name = "hdx-python-api" %}
{% set version = "5.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89930d8ff8dea899dc2fc9479032d1b81dbe95372d4db44ec8f8c91ae670da62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ckanapi >=4.7
    - defopt >=6.4.0
    - email_validator
    - hdx-python-country >=3.4.6
    - makefun
    - ndg-httpsclient
    - pyasn1
    - pyopenssl
    - quantulum3

test:
  imports:
    - hdx.api.configuration
    - hdx.api.locations
    - hdx.data.dataset
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://data.humdata.org
  summary: Python API for interacting with the HDX Data Porta
  description: |
    The HDX Python API Library is designed to enable you to easily develop code
    that interacts with the Humanitarian Data Exchange (HDX) platform. The
    major goal of the library is to make pushing and pulling data from HDX as
    simple as possible for the end user.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-api.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-api

extra:
  recipe-maintainers:
    - kynan
    - mcarans
