{% set name = "hdx-python-api" %}
{% set version = "6.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3bba518d2e354a8be0a0f0e2f7483ecbd143e64bcfb37d5f8cf152637d538cfe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - ckanapi >=4.8
    - defopt >=7.0.0
    - email_validator
    - hdx-python-country >=3.9.8
    - hdx-python-utilities >=3.9.6
    - libhxl >=5.2.2
    - makefun
    - quantulum3
    - requests

test:
  imports:
    - hdx.api.configuration
    - hdx.api.locations
    - hdx.data.dataset
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://data.humdata.org
  summary: Python API for interacting with the HDX Data Portal
  description: |
    The HDX Python API Library is designed to enable you to easily develop code
    that interacts with the Humanitarian Data Exchange (HDX) platform. The
    major goal of the library is to make pushing and pulling data from HDX as
    simple as possible for the end user.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-api.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-api

extra:
  recipe-maintainers:
    - kynan
    - mcarans
